# 线上配置文件
server:
  port: 8101
  servlet:
    session:
      cookie:
        max-age: 2592000
        # 解决跨域
        same-site: none
        secure: true
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kedaya
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
   # password: 123456
    # 文件上传
    servlet:
      multipart:
        # 大小限制
        max-file-size: 10MB
    # 分库分表配置
    shardingsphere:
      #数据源配置
      datasource:
        # 多数据源以逗号隔开即可
        names: kedaya
        kedaya:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://localhost:3306/kedaya
          username: root
          password: 123456
      # 规则配置
      rules:
        sharding:
          # 分片算法配置
          sharding-algorithms:
            # 自定义分片规则名
            answer-table-inline:
              ## inline 类型是简单的配置文件里面就能写的类型，其他还有自定义类等等
              type: INLINE
              props:
                algorithm-expression: user_answer_$->{appId % 2}
          tables:
            user_answer:
              actual-data-nodes: kedaya.user_answer_$->{0..1}
              # 分表策略
              table-strategy:
                standard:
                  sharding-column: appId
                  sharding-algorithm-name: answer-table-inline
# cos对象存储
cos:
  client:
    accessKey: AKIDLZbUFoCNODuRkZHmHrLdoriNp7D7oIZd
    secretKey: ubSAfz85rQegXCmjYFnCaqyvhHiy64sY
    region: ap-guangzhou
    bucket: yangjian-1336778056
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
# AI 配置
ai:
  apiKey: edc719950a27e177b56a4a9a67e0e350.BhFmO4d0i6uz5eMM
